# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Geneva2020
email: 
description: 
baseurl: "internation/" # the subpath of your site, e.g. /blog
url: "https://late-coffee.github.io/" # the base hostname & protocol for your site

# Navigation menu
navigation:
 - title: About
   url: /about.html
 - title: Memorandum
   url: /memorandum.html
 - title: Members
   url: /members.html
 - title: Glossary
   url: /glossary.html

# Social settings
500px_url: 
facebook_url: 
github_url: 
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url: 
slack_url: 
twitter_url: 

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: 
# Add one or more of the following
facebook:
  app_id: 
  publisher: 
  admins: 
logo:
google_site_verification: 

plugins:
  - jekyll-admin

sass:
  style: compressed
